version: "3"
services:
  db:
    build:
      context: ./database
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=p@ssw0rd"
    ports:
      - "1433:1433"
  backend:
    build:
      context: ./
      args:
        project_name: "Clubby"
    ports:
      - "8080:80"
